name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    # Generate executable file
    - name: Build
      run: go build -o server.out main.go

    - name: Beta-Release
      uses: actions/upload-artifact@v2
      with:
        name: server-beta.out
        path: server.out
